Repository wecode-bootcamp-korea/28-1st-MotherTerarosa-frontend, pull requests merged in 2022-01, with the labels that each got.

#4 [28기 박윤국] Add: pagination, products data fetch, skeleton UI 구현
  .eslintrc
  .prettierrc
  public/data/categories.json
  public/data/fakedata.md
  public/data/products.json
  public/images/fakedata.md
  public/index.html
  src/Hooks/README.md
  src/Hooks/useFetch.js
  src/Router.js
  src/config.js
  src/index.js
  src/pages/ShopList/Pagination/Pagination.jsx
  src/pages/ShopList/Pagination/Pagination.scss
  src/pages/ShopList/ProductList/ProductCard.jsx
  src/pages/ShopList/ProductList/ProductCard.scss
  src/pages/ShopList/ProductList/ProductList.jsx
  src/pages/ShopList/ShopAside/ShopAside.jsx
  src/pages/ShopList/ShopAside/ShopAside.scss
  src/pages/ShopList/ShopAside/ShopAsideWrapper.jsx
  src/pages/ShopList/ShopList.jsx
  src/pages/ShopList/ShopList.scss
  src/pages/ShopList/SkeletonShopList.jsx
  src/pages/ShopList/SkeletonShopList.scss
  src/styles/common.scss
  src/styles/config/constants/_colors.scss
  src/styles/index.scss
  src/utils/fetchData.js
  src/utils/printNumberWithComma.js
Labels: Status: Accepted

#6 [28기 성윤경]Add: global navigation 기본 기능, 추가 기능 구현 완료
  src/components/GlobalNav/GlobalNav.jsx
  src/components/GlobalNav/GlobalNav.scss
Labels: Status: 수정 요청

#2 [28기 엄성용] Add: Sign Up page 구현
  src/pages/Signup/Signup.jsx
  src/pages/Signup/Signup.scss
Labels: Status: 리뷰 요청

#13 Modify: parameter 옵션 변경
  src/Router.js
  src/pages/ShopList/ShopAside/ShopAside.jsx
  src/pages/ShopList/ShopList.jsx
Labels: Status: 리뷰 요청

#15 Fix : Link URL not fount, GNB 버그 수정 / ShopAside 컴포넌트 폴더로 이동 / 404 핸들링
  src/Router.js
  src/components/GlobalNav/GlobalNav.jsx
  src/components/GlobalNav/GlobalNav.scss
  src/components/ShopAside/ShopAside.jsx
  src/components/ShopAside/ShopAside.scss
  src/components/ShopAside/ShopAsideWrapper.jsx
  src/pages/NotFoundPage/NotFoundPage.jsx
  src/pages/NotFoundPage/NotFoundPage.scss
  src/pages/ShopList/ShopList.jsx
Labels: Status: 리뷰 요청

#16 [28기 엄성용] Add: Back End와 통신을 위한 branch
  src/config.js
  src/pages/Signup/Signup.jsx
Labels: Status: 리뷰 요청

#11 [28기 박윤국] Shop Detail Page 구현, 구매 Modal 구현
  public/data/product.json
  public/data/productDetail.json
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.scss
  src/components/ShopAside/ShopAside.jsx
  src/config.js
  src/pages/ShopDetail/ProductImageList/ProductImageArea.jsx
  src/pages/ShopDetail/ProductImageList/ProductImageList.jsx
  src/pages/ShopDetail/ProductInfo/ProductInfo.jsx
  src/pages/ShopDetail/ShopDetail.jsx
  src/pages/ShopDetail/ShopDetail.scss
  src/pages/ShopDetail/SkeletonShopDetail.jsx
  src/pages/ShopDetail/SkeletonShopDetail.scss
  src/styles/config/constants/_z-indexes.scss
Labels: Status: 리뷰 요청

#10 [28기 엄성용]Add: Login 구현
  src/pages/Login/Login.jsx
  src/pages/Login/Login.scss
Labels: Status: 리뷰 요청

#7 [28기 성윤경]Add : 메인페이지 캐러셀 수정완료, 프로덕트 리스트 구현완료
  package-lock.json
  package.json
  public/data/carousel_data.json
  public/images/best/best1.jpg
  public/images/best/best2.jpg
  public/images/best/best3.jpg
  public/images/carousel/01.jpg
  public/images/carousel/02.jpg
  public/images/carousel/03.jpg
  public/images/carousel/05.jpeg
  public/images/new/new1.jpg
  public/images/new/new2.jpg
  public/images/new/new3.jpg
  public/images/new/new4.jpg
  src/config.js
  src/pages/Main/Main.jsx
  src/pages/Main/Main.scss
  src/pages/Main/ProductsList/ProductCard/ProductCard.jsx
  src/pages/Main/ProductsList/ProductCard/ProductCard.scss
  src/pages/Main/ProductsList/ProductsList.jsx
  src/pages/Main/ProductsList/ProductsList.scss
  yarn.lock
Labels: Status: 수정 요청

#20 [28기 박윤국] Modify: Modal Layout 과 Modal Content 컴포넌트 분리
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.scss
  src/components/Modal/OrderModalForm/OrderModal.jsx
  src/components/Modal/OrderModalForm/OrderModal.scss
  src/pages/ShopDetail/ShopDetail.jsx
Labels: Status: 리뷰 요청

#21 [28기 박윤국] 통신관련 통합 테스트
  src/Hooks/README.md
  src/components/Modal/OrderModalForm/OrderModal.jsx
  src/config.js
  src/pages/Login/Login.jsx
  src/pages/Login/Login.scss
  src/pages/ShopDetail/ShopDetail.jsx
  src/pages/Signup/Signup.jsx
Labels: Status: 리뷰 요청
